### ISSUE TITLE
Develop tests

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/origami.js#10]
Question: How to test canvas with animation?

**Comment by douglasrocha** [comment]
There are two possible ways that I'm aware of.

1. You can use JS-ImageDiff Jasmine to check whether your results are what you expect (http://humblesoftware.github.io/js-imagediff/test.html)

2. You can append all of your canvas calls to a list and check whether the calls follow the ones you define on your test case on the same order you expect.

**Comment by raphamorim** [comment]
I had thought the second option. But the first seems to be interesting.

**Comment by raphamorim** [comment]
Tests wishlist

- [x] Init behavior Test 
- [] Tests Shapes
  - [] Rect
  - [] Arc
  - [] Text
  - [] Image
  - [] Polygon
  - [] Sprite
  - [] Shape
  - [] Line
- [] Resources Tests

**Comment by raphamorim** [comment]
Ref: 8210941e55987d4ab95e70bf866bdaed4fadc94f

**Comment by raphamorim** [comment]
Ref: c09fdae11a84130fb55c036f7f59caa4c25bff0a
