### ISSUE TITLE
A Markup Language to draw with Origami

### ISSUE THREAD

**Issue by leocavalcante** [raphamorim/origami.js#12]
How about a XML-based language to draw with Origami API?
It's a very common pattern for representing a display list/UI, from SVG to MXML and now JSX.

Just played around with DOMParse:
http://www.es6fiddle.net/iju78rqa/

**Comment by raphamorim** [comment]
I personally think a great idea. But to begin to develop, we need to adjust/add the tests and make origami.js stable.
I will put this issue to consider in a future roadmap (probably `v1.0.0`)

**Comment by raphamorim** [comment]
Ref: #10

**Comment by leocavalcante** [comment]
Cool. Agreed about delaying to before it has some tests.

**Comment by leocavalcante** [comment]
Well,
Don't know how the project is going, but just saw this project and it remembers this issue:
- http://tparisi.github.io/glam/docs/#Manual/Introduction/#What-is-GLAM
Declarative way is pretty great for graphical stuff and XML-based markups and very common.

**Comment by raphamorim** [comment]
I think now Origami is stable, we can think about it @leocavalcante.

[Aframe](https://aframe.io) uses a similar approach, what do you think?
