### ISSUE TITLE
Broken links and Status

### ISSUE THREAD

**Issue by HighOnDrive** [raphamorim/origami.js#32]
Just to let you know, most header links on http://origamijs.com are not working. What is the status of Origami.js? It looks quite robust and I'd be interested in it's future plans.

**Comment by raphamorim** [comment]
Hi, @HighOnDrive 

The site (**[origamijs.com](http://origamijs.com)**) it's currently under development, you can help us in [github.com/raphamorim/origamijs.com](https://github.com/raphamorim/origamijs.com). 

But the origamijs can it's available for use. However doesn't have a site with docs and showcases yet :/
