### ISSUE TITLE
Principles of animation

### ISSUE THREAD

**Issue by raphamorim** [raphamorim/origami.js#37]
Ref:
- [Animation of Life](https://vimeo.com/93206523) 
- [12 Basic Principles of Animation](https://en.wikipedia.org/wiki/12_basic_principles_of_animation)

**Comment by ntmedina** [comment]
https://s-media-cache-ak0.pinimg.com/originals/8a/e5/c8/8ae5c8b253ce37b9876ce464e0d396c4.gif
I hope this can help :)
